project:
  type: website

website:
  title: "ML-Blog-Posts"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/hassledw
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-hassler-85027a21a/
format:
  html:
    theme: cyborg
    css: styles.css



